blank_issues_enabled: false
name: template
description: creation de nouvel element
title: ""
labels: []
projects: []
assignees:
  - lukackx
body:
  - type: markdown
    attributes: 
      value: "test"
